# Codespell on markdown files to avoid typos in the list with links
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        files: \.md$
